# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppGaussianKernel <- function(x) {
    .Call('MeanShift_RcppGaussianKernel', PACKAGE = 'MeanShift', x)
}

RcppExponentialKernel <- function(x) {
    .Call('MeanShift_RcppExponentialKernel', PACKAGE = 'MeanShift', x)
}

RcppCubicKernel <- function(x) {
    .Call('MeanShift_RcppCubicKernel', PACKAGE = 'MeanShift', x)
}

RcppEpanechnikovKernel <- function(x) {
    .Call('MeanShift_RcppEpanechnikovKernel', PACKAGE = 'MeanShift', x)
}

RcppDistanceFunction <- function(x, y) {
    .Call('MeanShift_RcppDistanceFunction', PACKAGE = 'MeanShift', x, y)
}

RcppBlurringMeanShiftOperator <- function(x, h, kernel) {
    .Call('MeanShift_RcppBlurringMeanShiftOperator', PACKAGE = 'MeanShift', x, h, kernel)
}

RcppBlurringMeanShiftAlgorithm <- function(x, h, kernel, tol_stop, max_iter) {
    .Call('MeanShift_RcppBlurringMeanShiftAlgorithm', PACKAGE = 'MeanShift', x, h, kernel, tol_stop, max_iter)
}

RcppMeanShiftOperator <- function(x, points, h, kernel) {
    .Call('MeanShift_RcppMeanShiftOperator', PACKAGE = 'MeanShift', x, points, h, kernel)
}

RcppMeanShiftAlgorithm <- function(x, points, h, kernel, tol_stop) {
    .Call('MeanShift_RcppMeanShiftAlgorithm', PACKAGE = 'MeanShift', x, points, h, kernel, tol_stop)
}

